<?php
declare(strict_types=1);

namespace App\Domain\Enum;

enum ExceptionCodes: int
{
    // Logger
    case LOGGER_CREATION_FAILED = 1501;

    // Database
    case DB_INVALID_CREDENTIALS = 1001;
    case DB_CONNECTION_FAILED = 1002;
    case DB_QUERY_FAILED = 1003;

    // User exceptions (2000-2999)
    case USER_INVALID_ID = 2001;
    case USER_NOT_FOUND = 2002;
    case USER_ALREADY_EXISTS = 2003;
    case USER_EMPTY_FIELDS = 2004;
    case USER_USERNAME_TAKEN = 2005;
    case USER_UNAUTHORIZED = 2006;
    case USER_CANNOT_DELETE_SELF = 2007;
    case USER_CREATE_FAILED = 2008;
    case USER_DELETE_FAILED = 2009;

    // Validation exceptions (3000-3999)
    case VALIDATION_FAILED = 3001;
    case INVALID_INPUT = 3002;

    // WEB RELATED
    case INVALID_CSRF = 4001;
    case MISSING_CSRF = 4002;

    // Auth
    case AUTH_INVALID_CREDENTIALS = 5001;
    case AUTH_EMPTY_CREDENTIALS = 5002;
    case AUTH_USER_NOT_FOUND = 5003;
    case AUTH_USER_UNAUTHORIZED = 5004;
    case AUTH_USER_NOT_LOGGED_IN = 5005;

    // Announcement
    case ANNOUNCEMENT_INVALID_ID = 6001;
    case ANNOUNCEMENT_EMPTY_TITLE = 6002;
    case ANNOUNCEMENT_EMPTY_TEXT = 6003;
    case ANNOUNCEMENT_INVALID_VALID_UNTIL = 6004;
    case ANNOUNCEMENT_NOT_FOUND = 6005;
    case ANNOUNCEMENT_CREATE_FAILED = 6006;
    case ANNOUNCEMENT_DELETE_FAILED = 6007;
    case ANNOUNCEMENT_UPDATE_FAILED = 6008;
    case ANNOUNCEMENT_STATUS_UPDATE_FAILED = 6009;
    case ANNOUNCEMENT_NO_CHANGES = 6010;
    case ANNOUNCEMENT_INVALID_STATUS = 6011;
    case ANNOUNCEMENT_TITLE_TOO_SHORT = 6012;
    case ANNOUNCEMENT_TEXT_TOO_SHORT = 6013;
    case ANNOUNCEMENT_TITLE_TOO_LONG = 6014;
    case ANNOUNCEMENT_TEXT_TOO_LONG = 6015;
    case ANNOUNCEMENT_EXPIRATION_TOO_FAR_IN_THE_FUTURE = 6016;
    case ANNOUNCEMENT_EXPIRATION_IN_THE_PAST = 6017;

    // Countdown
    case COUNTDOWN_INVALID_ID = 7001;
    case COUNTDOWN_EMPTY_FIELDS = 7002;
    case COUNTDOWN_INVALID_DATE_FORMAT = 7003;
    case COUNTDOWN_NOT_FOUND = 7004;
    case COUNTDOWN_NO_CHANGES = 7005;
    case COUNTDOWN_CREATE_FAILED = 7006;
    case COUNTDOWN_UPDATE_FAILED = 7007;
    case COUNTDOWN_DELETE_FAILED = 7008;
    case COUNTDOWN_TITLE_TOO_SHORT = 7009;
    case COUNTDOWN_TITLE_TOO_LONG = 7010;
    case COUNTDOWN_COUNT_TO_IN_THE_PAST = 7011;
    case COUNTDOWN_FETCH_FAILED = 7012;


    case MODULE_INVALID_ID = 8001;
    case MODULE_NOT_FOUND = 8002;
    case MODULE_INVALID_TIME_FORMAT = 8003;
    case MODULE_UPDATE_FAILED = 8004;
    case MODULE_TOGGLE_FAILED = 8005;

    case VIEW_USER_NOT_AUTHENTICATED = 9001;
    case VIEW_LOAD_FAILED = 9002;
    case VIEW_MISSING_DATA = 9003;

    case DISPLAY_MODULE_NOT_VISIBLE = 10001;
    case DISPLAY_FETCH_DEPARTURES_FAILED = 10002;
    case DISPLAY_FETCH_ANNOUNCEMENTS_FAILED = 10003;
    case DISPLAY_FETCH_COUNTDOWN_FAILED = 10004;
    case DISPLAY_FETCH_WEATHER_FAILED = 1005;
    case DISPLAY_FETCH_QUOTE_FAILED = 1006;
    case DISPLAY_FETCH_WORD_FAILED = 1007;
}
