<?php
declare(strict_types=1);

namespace App\Domain\Shared;

enum DomainExceptionCodes: string
{
    // Logger
    case LOGGER_CREATION_FAILED = "LOGGER_CREATION_FAILED";

    // Database
    case DB_INVALID_CREDENTIALS = "DB_INVALID_CREDENTIALS";
    case DB_CONNECTION_FAILED = "DB_CONNECTION_FAILED";
    case DB_QUERY_FAILED = "DB_QUERY_FAILED";

    // User exceptions (2000-2999)
    case USER_INVALID_ID = "USER_INVALID_ID";
    case USER_NOT_FOUND = "USER_NOT_FOUND";
    case USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
    case USER_EMPTY_FIELDS = "USER_EMPTY_FIELDS";
    case USER_USERNAME_TAKEN = "USER_USERNAME_TAKEN";
    case USER_UNAUTHORIZED = "USER_UNAUTHORIZED";
    case USER_CANNOT_DELETE_SELF = "USER_CANNOT_DELETE_SELF";
    case USER_CREATE_FAILED = "USER_CREATE_FAILED";
    case USER_DELETE_FAILED = "USER_DELETE_FAILED";

    // Validation exceptions (3000-3999)
    case VALIDATION_FAILED = "VALIDATION_FAILED";
    case INVALID_INPUT = "INVALID_INPUT";

    // WEB RELATED
    case INVALID_CSRF = "INVALID_CSRF";
    case MISSING_CSRF = "MISSING_CSRF";
    case INVALID_DATETIME = "INVALID_DATETIME";
    CASE MISSING_PARAMETER = "MISSING_PARAMETER";

    // Auth
    case AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS";
    case AUTH_EMPTY_CREDENTIALS = "AUTH_EMPTY_CREDENTIALS";
    case AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND";
    case AUTH_USER_UNAUTHORIZED = "AUTH_USER_UNAUTHORIZED";
    case AUTH_USER_NOT_LOGGED_IN = "AUTH_USER_NOT_LOGGED_IN";

    // Announcement
    case ANNOUNCEMENT_INVALID_ID = "ANNOUNCEMENT_INVALID_ID";
    case ANNOUNCEMENT_EMPTY_TITLE = "ANNOUNCEMENT_EMPTY_TITLE";
    case ANNOUNCEMENT_EMPTY_TEXT = "ANNOUNCEMENT_EMPTY_TEXT";
    case ANNOUNCEMENT_INVALID_VALID_UNTIL = "ANNOUNCEMENT_INVALID_VALID_UNTIL";
    case ANNOUNCEMENT_NOT_FOUND = "ANNOUNCEMENT_NOT_FOUND";
    case ANNOUNCEMENT_CREATE_FAILED = "ANNOUNCEMENT_CREATE_FAILED";
    case ANNOUNCEMENT_DELETE_FAILED = "ANNOUNCEMENT_DELETE_FAILED";
    case ANNOUNCEMENT_UPDATE_FAILED = "ANNOUNCEMENT_UPDATE_FAILED";
    case ANNOUNCEMENT_STATUS_UPDATE_FAILED = "ANNOUNCEMENT_STATUS_UPDATE_FAILED";
    case ANNOUNCEMENT_NO_CHANGES = "ANNOUNCEMENT_NO_CHANGES";
    case ANNOUNCEMENT_INVALID_STATUS = "ANNOUNCEMENT_INVALID_STATUS";
    case ANNOUNCEMENT_TITLE_TOO_SHORT = "ANNOUNCEMENT_TITLE_TOO_SHORT";
    case ANNOUNCEMENT_TEXT_TOO_SHORT = "ANNOUNCEMENT_TEXT_TOO_SHORT";
    case ANNOUNCEMENT_TITLE_TOO_LONG = "ANNOUNCEMENT_TITLE_TOO_LONG";
    case ANNOUNCEMENT_TEXT_TOO_LONG = "ANNOUNCEMENT_TEXT_TOO_LONG";
    case ANNOUNCEMENT_EXPIRATION_TOO_FAR_IN_THE_FUTURE = "ANNOUNCEMENT_EXPIRATION_TOO_FAR_IN_THE_FUTURE";
    case ANNOUNCEMENT_EXPIRATION_IN_THE_PAST = "ANNOUNCEMENT_EXPIRATION_IN_THE_PAST";

    // Countdown
    case COUNTDOWN_INVALID_ID = "COUNTDOWN_INVALID_ID";
    case COUNTDOWN_EMPTY_FIELDS = "COUNTDOWN_EMPTY_FIELDS";
    case COUNTDOWN_INVALID_DATE_FORMAT = "COUNTDOWN_INVALID_DATE_FORMAT";
    case COUNTDOWN_NOT_FOUND = "COUNTDOWN_NOT_FOUND";
    case COUNTDOWN_NO_CHANGES = "COUNTDOWN_NO_CHANGES";
    case COUNTDOWN_CREATE_FAILED = "COUNTDOWN_CREATE_FAILED";
    case COUNTDOWN_UPDATE_FAILED = "COUNTDOWN_UPDATE_FAILED";
    case COUNTDOWN_DELETE_FAILED = "COUNTDOWN_DELETE_FAILED";
    case COUNTDOWN_TITLE_TOO_SHORT = "COUNTDOWN_TITLE_TOO_SHORT";
    case COUNTDOWN_TITLE_TOO_LONG = "COUNTDOWN_TITLE_TOO_LONG";
    case COUNTDOWN_COUNT_TO_IN_THE_PAST = "COUNTDOWN_COUNT_TO_IN_THE_PAST";
    case COUNTDOWN_FETCH_FAILED = "COUNTDOWN_FETCH_FAILED";


    case MODULE_INVALID_ID = "MODULE_INVALID_ID";
    case MODULE_NOT_FOUND = "MODULE_NOT_FOUND";
    case MODULE_INVALID_TIME_FORMAT = "MODULE_INVALID_TIME_FORMAT";
    case MODULE_UPDATE_FAILED = "MODULE_UPDATE_FAILED";
    case MODULE_TOGGLE_FAILED = "MODULE_TOGGLE_FAILED";
    case MODULE_INVALID_NAME = "MODULE_INVALID_NAME";

    case VIEW_USER_NOT_AUTHENTICATED = "VIEW_USER_NOT_AUTHENTICATED";
    case VIEW_LOAD_FAILED = "VIEW_LOAD_FAILED";
    case VIEW_MISSING_DATA = "VIEW_MISSING_DATA";

    case DISPLAY_MODULE_NOT_VISIBLE = "DISPLAY_MODULE_NOT_VISIBLE";
    case DISPLAY_FETCH_DEPARTURES_FAILED = "DISPLAY_FETCH_DEPARTURES_FAILED";
    case DISPLAY_FETCH_ANNOUNCEMENTS_FAILED = "DISPLAY_FETCH_ANNOUNCEMENTS_FAILED";
    case DISPLAY_FETCH_COUNTDOWN_FAILED = "DISPLAY_FETCH_COUNTDOWN_FAILED";
    case DISPLAY_FETCH_WEATHER_FAILED = "DISPLAY_FETCH_WEATHER_FAILED";
    case DISPLAY_FETCH_QUOTE_FAILED = "DISPLAY_FETCH_QUOTE_FAILED";
    case DISPLAY_FETCH_WORD_FAILED = "DISPLAY_FETCH_WORD_FAILED";
}
